language: rust
rust:
  - 1.0.0
  - beta
  - nightly
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose
  - |
    (for feature in '' bigint rational complex; do
      cargo test --verbose --no-default-features --features="$feature" || exit 1
    done)
  - |
    [ $TRAVIS_RUST_VERSION != nightly ] || (
      cargo bench &&
      cargo test --verbose --manifest-path=num-macros/Cargo.toml
    )
  - cargo doc
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = nightly ] &&
  openssl aes-256-cbc -K $encrypted_9e86330b283d_key -iv $encrypted_9e86330b283d_iv -in .travis/deploy.enc -out ./travis/deploy -d &&
  chmod 600 ./travis/deploy &&
  ssh-add ./travis/deploy &&
  pip install ghp-import --user $USER &&
  cp doc/index.html target/doc/ &&
  $HOME/.local/bin/ghp-import -n target/doc &&
  git push -qf ssh://git@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
notifications:
  email:
    on_success: never
