[package]
authors = ["The Rust Project Developers"]
description = "Big integer implementation for Rust"
documentation = "https://docs.rs/num-bigint"
homepage = "https://github.com/rust-num/num-bigint"
keywords = ["mathematics", "numerics", "bignum"]
categories = [ "algorithms", "data-structures", "science" ]
license = "MIT/Apache-2.0"
name = "num-bigint"
repository = "https://github.com/rust-num/num-bigint"
version = "0.2.0-git"
publish = false
readme = "README.md"
build = "build.rs"

[[bench]]
name = "bigint"

[[bench]]
name = "factorial"

[[bench]]
name = "gcd"

[[bench]]
harness = false
name = "shootout-pidigits"

[dependencies]

[dependencies.num-integer]
version = "0.1.38"
default-features = false

[dependencies.num-traits]
version = "0.2.4"
default-features = false
features = ["std"]

[dependencies.rand]
optional = true
version = "0.4"

[dependencies.serde]
optional = true
version = "1.0"

[dev-dependencies]
serde_test = "1.0"

[dev-dependencies.rand]
version = "0.4"

[features]
default = []
i128 = ["num-integer/i128", "num-traits/i128"]
