[package]
authors = ["The Rust Project Developers"]
description = "A collection of numeric types and traits for Rust, including bigint,\ncomplex, rational, range iterators, generic integers, and more!\n"
documentation = "http://rust-num.github.io/num"
homepage = "https://github.com/rust-num/num"
keywords = ["mathematics", "numerics"]
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-num/num"
name = "num"
version = "0.1.31"

[[bench]]
name = "bigint"

[[bench]]
harness = false
name = "shootout-pidigits"

[dependencies]

[dependencies.num-bigint]
optional = true
path = "bigint"

[dependencies.num-complex]
optional = true
path = "complex"

[dependencies.num-integer]
path = "./integer"

[dependencies.num-iter]
optional = false
path = "iter"

[dependencies.num-rational]
optional = true
path = "rational"

[dependencies.num-traits]
path = "./traits"

[dev-dependencies]

[dev-dependencies.rand]
version = "0.3.8"

[features]
bigint = ["num-bigint"]
complex = ["num-complex"]
rational = ["num-rational"]
default = ["bigint", "complex", "rational", "rustc-serialize"]

serde = [
  "num-bigint/serde",
  "num-complex/serde",
  "num-rational/serde"
]
rustc-serialize = [
  "num-bigint/rustc-serialize",
  "num-complex/rustc-serialize",
  "num-rational/rustc-serialize"
]
