[package]

name = "num"
version = "0.0.3"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/rust-lang/num"
repository = "https://github.com/rust-lang/num"

description = """
Simple numerics. This crate contains basic arbitrary-sized integer,
rational, and complex types.
"""
