[package]
authors = ["The Rust Project Developers"]
description = "A collection of numeric types and traits for Rust, including bigint,\ncomplex, rational, range iterators, generic integers, and more!\n"
documentation = "http://rust-num.github.io/num"
homepage = "https://github.com/rust-num/num"
keywords = ["mathematics", "numerics"]
license = "MIT/Apache-2.0"
name = "num"
repository = "https://github.com/rust-num/num"
version = "0.1.31"

[[bench]]
name = "bigint"

[[bench]]
harness = false
name = "shootout-pidigits"

[dependencies]

[dependencies.num-bigint]
optional = true
path = "bigint"

[dependencies.num-integer]
path = "./integer"

[dependencies.num-rational]
optional = true
path = "rational"

[dependencies.num-traits]
path = "./traits"

[dependencies.rand]
optional = true
version = "0.3.8"

[dependencies.rustc-serialize]
optional = true
version = "0.3.13"

[dependencies.serde]
optional = true
version = "^0.7.0"

[dev-dependencies]

[dev-dependencies.rand]
version = "0.3.8"

[features]
bigint = ["num-bigint"]
complex = []
default = ["bigint", "complex", "rand", "rational", "rustc-serialize"]
rational = ["num-rational"]
